# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SanSIUChi.com
email: scot0320@snu.ac.kr
description: Penseive - Everything about me
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sansiuchicom.github.io" # the base hostname & protocol for your site
linked_in: www.linkedin.com/in/seoktae-kim-1b82b0213
github_username:  sansiuchicom
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
